### ISSUE TITLE
where is download Resources/word_list_xx.txt

### ISSUE THREAD

**Issue by zuoyebushiwo** [D-Mitt/burst-trie#1]
can you provide this files, thanks

**Comment by D-Mitt** [comment]
Hey, I think I blew it away after I worked on this as it was taking up too much space on my hard drive. I was just using it for testing for a research paper (you may be able to refind the files I used from Reuters - check the paper I provided). Otherwise, you can populate it with anything, although you might have to write your own parser depending on the file format.

Thanks.

**Comment by zuoyebushiwo** [comment]
thanks.I know what you mean after you say
